language: c

cache: apt

sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_script:
  - pushd /tmp
  - mkdir libbtbb-install
  - wget https://github.com/greatscottgadgets/libbtbb/archive/master.zip -O /tmp/libbtbb-master.zip
  - unzip libbtbb-master.zip
  - mkdir libbtbb-master/build
  - pushd libbtbb-master/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/libbtbb-install ..
  - make
  - make install
  - popd
  - popd
  - export CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libusb; fi

script:
  - mkdir host/build
  - pushd host/build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then DYLIB_SUFFIX=dylib; else DYLIB_SUFFIX=so; fi
  - cmake -DLIBBTBB_INCLUDE_DIR=/tmp/libbtbb-install/include -DLIBBTBB_LIBRARIES=/tmp/libbtbb-install/lib/libbtbb.$DYLIB_SUFFIX ..
  - make
  - popd
  - pushd firmware
  - DFU_TOOL="../../host/build/ubertooth-tools/src/ubertooth-dfu" make

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libusb-1.0-0-dev
      - libbluetooth-dev
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
